name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Jerred Shepherd (RiotShielder)
website: http://shepherdjerred.com/

main: com.shepherdjerred.class.Main

commands:
    plugin:
        description: Description
        aliases: []

permissions:
    plugin.permission:
        description: Description
        default: true